### ISSUE TITLE
Possible race condition in voyager_bootloader_process_receieved_packet()

### ISSUE THREAD

**Issue by rhempel** [sahil-kale/voyager-bootloader#49]
There is a function called voyager_bootloader_process_receieved_packet() that may be called asynchronously to let the bootloader know that the next packet can be processed.

There may be a bug in this function as voyager_data.pending_data is set to true before the length and message buffer are valid - this should probably be done AFTER they are valid :-)

**Comment by sahil-kale** [comment]
You are absolutely right!
